// =============================================================================
// Module      : heart_rate_top
// Description : Top-level FPGA Heart Rate Monitor.
//               Instantiates the peak_detector and bpm_calculator modules
//               and wires them together.
//
//               Data path:
//                 adc_raw [12-bit] → peak_detector → beat_pulse → bpm_calculator → bpm [8-bit]
//
// Target      : Xilinx 7-Series / Artix-7 (Vivado synthesizable)
// Clock       : 100 MHz
// Author      : [Your Name]  |  Date: 2026
//
// Pin assignments (example for Basys3):
//   clk      → W5  (100 MHz onboard oscillator)
//   rst      → U18 (BTNC center button)
//   adc_raw  → Pmod header JA (12-bit, padded to 16 pins if needed)
//   bpm      → seven-segment or LED[7:0]
// =============================================================================

`timescale 1ns / 1ps   // Simulation timescale: 1 ns resolution, 1 ps precision

module heart_rate_top #(
    // -------------------------------------------------------------------------
    // These parameters bubble down into the sub-modules.
    // Change them here to reconfigure the entire design without editing RTL.
    // -------------------------------------------------------------------------
    parameter CLK_FREQ         = 100_000_000,  // 100 MHz
    parameter THRESHOLD        = 12'h800,       // R-peak detection threshold
    parameter REFRACTORY_CYCLES = 30_000_000,  // ~300 ms @ 100 MHz
    parameter BPM_MIN          = 8'd40,
    parameter BPM_MAX          = 8'd180
)(
    input  wire        clk,       // 100 MHz FPGA system clock
    input  wire        rst,       // Active-high synchronous reset (e.g., button)
    input  wire [11:0] adc_raw,   // 12-bit ECG/ADC sample (new sample each cycle or slower)
    output wire [7:0]  bpm        // Calculated heart rate in BPM
);

    // -------------------------------------------------------------------------
    // Internal signal: beat_pulse
    // A single-clock-cycle HIGH pulse generated by peak_detector each time
    // an R-peak is detected. Feeds directly into bpm_calculator.
    // -------------------------------------------------------------------------
    wire beat_pulse;

    // =========================================================================
    // Instantiation 1: peak_detector
    // Monitors adc_raw and fires beat_pulse on each confirmed R-peak.
    // =========================================================================
    peak_detector #(
        .THRESHOLD        (THRESHOLD),
        .REFRACTORY_CYCLES(REFRACTORY_CYCLES)
    ) u_peak_detector (
        .clk        (clk),
        .rst        (rst),
        .adc_raw    (adc_raw),
        .beat_pulse (beat_pulse)
    );

    // =========================================================================
    // Instantiation 2: bpm_calculator
    // Measures R-R intervals and computes BPM from consecutive beat pulses.
    // =========================================================================
    bpm_calculator #(
        .CLK_FREQ  (CLK_FREQ),
        .BPM_MIN   (BPM_MIN),
        .BPM_MAX   (BPM_MAX)
    ) u_bpm_calculator (
        .clk        (clk),
        .rst        (rst),
        .beat_pulse (beat_pulse),
        .bpm        (bpm)
    );

endmodule
